# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: dm4bem
author: Christian Ghiaus
copyright: "2024"
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: dm4bem_book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cghiaus/dm4bem_book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  base_url: https://cghiaus.github.io/dm4bem_book/
  use_issues_button: true
  use_repository_button: true

# Added according to https://jupyterbook.org/interactive/launchbuttons.html

# Control the notebook interface that opens
# Add a Launch on Binder button
# launch_buttons:
#   notebook_interface: "jupyterlab"  # or "classic"
#   binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
