name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.11.11
  - jupyter=1.0.0
  - jupyterlab=4.3.4
  - matplotlib=3.9.2
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.3
  - control=0.10.0
